### ISSUE TITLE
Error indexing a custom contact text file

### ISSUE THREAD

**Issue by RXCoux** [4dn-dcic/pairix#39]
Hi, thanks a lot for making and maintaining all these very useful tools. 

I have a custom made contact pairs file in the following format chr1 10000 20000 chr2 30000 50000 3.5 

that I'm trying to index using pairix to load in cooler. I tried
>pairix -s 1 -d 4 -b 2 -e 3 -u 5 -v 6 -T 3R.txt.gz

but I get

[get_intv] the following line cannot be parsed and skipped: chr3R	0	20000	chr3R	40000	60000	252

[ti_index_core] the indexes overlap or are out of bounds

It's the 1st line of my file and I don't really understand the error, my file only contains contacts for chr3R as I'm only interested in intra-chromosomal contacts.

[3R.txt.gz](https://github.com/4dn-dcic/pairix/files/1293104/3R.txt.gz)

Could you please let me know if this error is reproducible or if I'm doing something wrong?
Thanks in advance

**Comment by SooLee** [comment]
Hi, looks like your line is tab-delimited. Do you want to try without the
-T option? The -T option assumes the file is space-delimited.

**Comment by RXCoux** [comment]
Thanks that was a stupid mistake, my bad - it indeed worked
