### ISSUE TITLE
assume symmetrical query

### ISSUE THREAD

**Issue by blajoie** [4dn-dcic/pairix#41]
First - love the tool, worked right out of the box.
2D queries on BEDPE will be quite powerful, looking forward to formal tabix support!

One suggestion, if one queries via only a single coordinate, can the tool assume a symmetrical query?
e.g.  change query internally
pairix -h test.bedpe.gz '1:1387294-1468095'
to
pairix -h test.bedpe.gz '1:1387294-1468095|1:1387294-1468095'

The command, "pairix -h test.bedpe.gz '1:1387294-1468095'" currently returns nothing,  I would suspect  most users would intend for the tool to run the query, "pairix -h test.bedpe.gz '1:1387294-1468095|1:1387294-1468095'", given the original input.

Thoughts?

**Comment by SooLee** [comment]
Hi blajoie,

Thank you for your feedback! That's a very good point. Will be in in the next version. :)

Best,
Soo
