### ISSUE TITLE
executing get_blocknames() twices crashes Python

### ISSUE THREAD

**Issue by golobor** [4dn-dcic/pairix#51]
Hi,
I've found that executing get_blocknames() twice crashes the whole python session:

f = pypairix.open(pairs_path)
f.get_blocknames()
f.get_blocknames()

**Comment by SooLee** [comment]
Thanks, Anton. Looking at it now!

**Comment by golobor** [comment]
the problem is actually even worse - in my ipython console get_blocknames() crashes at the first execution

**Comment by SooLee** [comment]
fixed now
