### ISSUE TITLE
Integer overflow for -n option: reporting negative numbers!

### ISSUE THREAD

**Issue by mimakaev** [4dn-dcic/pairix#58]
At least it is observed on the largest Bonev dataset. 

magus@wiz:~/work/distillate/rao2014Test$ pairix -n HiC_NPC_4.nodups.pairs.gz
-2003369355

**Comment by mimakaev** [comment]
@SooLee   The issue is still present as of pairix 0.3.6.

**Comment by sergpolly** [comment]
little update on this one:
I was running the same test - Bonev 2017 and got an error while dealing with the same library `HiC_NPC_4.nodups.pairs.gz` (the largest one)

In my case however, `pairix -n ` is doing fine:
![screenshot from 2018-12-26 15-29-40](https://user-images.githubusercontent.com/6790270/50456866-80bfbc80-0925-11e9-8e43-33845dbca0dc.png)

But! `pypairix` is not so great:
![screenshot from 2018-12-26 15-37-29](https://user-images.githubusercontent.com/6790270/50456880-946b2300-0925-11e9-902e-39150a0c1aea.png)

The value itself 2.3 billion is indeed > `int32` upper limit.

@nvictus suggests that the `int32` overflow happens here: https://github.com/4dn-dcic/pairix/blob/master/src/pairixmodule.c#L594

pairix version
![screenshot from 2018-12-26 15-32-20](https://user-images.githubusercontent.com/6790270/50456892-a4830280-0925-11e9-913a-132b56376e2d.png)

**Comment by nvictus** [comment]
I suspect a downcast to int32 is happening upon converting to a Python int due to the `i` argument. See https://docs.python.org/3/c-api/arg.html#c.Py_BuildValue

**Comment by SooLee** [comment]
@mimakaev My apology - I saw this issue just now. Haven't had a chance to work on pairix for some time. I should check more often! If you do `pairix index` with `0.3.6` before `pairix -n`, do you still have the problem? The linecount is saved during the indexing. `0.3.6` Doesn't fix the overflow from a previously indexed pairs file. It works with previous indexes but it does not correct for the overflow. I could add that feature to `0.3.7`.

**Comment by SooLee** [comment]
@sergpolly @nvictus Thanks for reporting the problem with pypairix! Apologies for not noticing the issue earlier. We're look into it right now.

**Comment by SooLee** [comment]
The pypairix `get_linecount` issue is now fixed in `0.3.7`.
