### ISSUE TITLE
Is there a binary spec for the pairix format?

### ISSUE THREAD

**Issue by cmdcolin** [4dn-dcic/pairix#60]
Hi there, is a binary spec for pairix or if not just some code I could reference to understand? Thanks :)

**Comment by SooLee** [comment]
@cmdcolin Apology for not noticing the issue until now! We don't have a binary version for the pairs format. The source code for reading and writing pairix index is in the `src` folder of the repo. It was written on top of tabix, and the basic concept is the same with just a slight modification.

**Comment by cmdcolin** [comment]
Sorry for not providing more info. I guess my angle is that I was interested in possibly rewriting a different implementation and needed to just get deep into the implementation to do so. I was curious if the index file is a plain tabix file and then what source code helps in doing the queries (probably need full 2d queries)

**Comment by SooLee** [comment]
@cmdcolin The index file is a modification from a tabix file, so it wouldn't work with a regular tabix index. Most of the C source code related to building and using index is in `src/index.c`. I think modifying this file would be sufficient in most cases, though there are other source files in `src` directory that handle more internal stuff like implementing hash used for the index, etc. Does this answer your question?

**Comment by cmdcolin** [comment]
My target would be a making a reader of the format for a different language so having a file format specification would be useful similar to hts-specs docs

**Comment by SooLee** [comment]
We have pypairix for Python (`src/pairixmodule.c`) and Rpairix for R (https://github.com/4dn-dcic/Rpairix) but both of them use the same underlying C source (`src/index.c`), so that could be one possibility.

The structure of the index is defined in the same C file.

I will see if I can make a documentation for the index structure.

**Comment by cmdcolin** [comment]
Thanks, it would be a reimplementation would be from scratch instead of via the C source code most likely (javascript) so file spec would be handy

**Comment by SooLee** [comment]
@cmdcolin My apology for the delay. Here is the index spec. Please let me know if this is what you were looking for. https://github.com/4dn-dcic/pairix/blob/master/pairix_index_spec.pdf
