### ISSUE TITLE
Converting pairs to merged_nodups

### ISSUE THREAD

**Issue by papelypluma** [4dn-dcic/pairix#67]
Hi pairix developers! I'd like to explore if it's possible by any chance to convert pairs file to merged_nodups file using pairix? There's a script in pairix that does the reverse though. 

Thanks a lot!

**Comment by SooLee** [comment]
Hi @papelypluma Sorry we currently don't have an option to convert pairs to merged_nodups. But juicer_tools does take in the pairs format so you may not have to convert it if that's how you wanted to use the merge_nodups. If you do need to convert, you could try awk to rearrange the columns?

**Comment by papelypluma** [comment]
Hi @SooLee, thanks much for the response and suggestion! I'll move forward with this idea.
